// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gate2Game.proto

#ifndef PROTOBUF_Gate2Game_2eproto__INCLUDED
#define PROTOBUF_Gate2Game_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace MPMsg {
class GameUserLogonSuccess_Game2Gate;
class GameUserLogonSuccess_Game2GateDefaultTypeInternal;
extern GameUserLogonSuccess_Game2GateDefaultTypeInternal _GameUserLogonSuccess_Game2Gate_default_instance_;
class GameUserLogonSuccess_Gate2Game;
class GameUserLogonSuccess_Gate2GameDefaultTypeInternal;
extern GameUserLogonSuccess_Gate2GameDefaultTypeInternal _GameUserLogonSuccess_Gate2Game_default_instance_;
class GateUserLogoutRet_Game2Gate;
class GateUserLogoutRet_Game2GateDefaultTypeInternal;
extern GateUserLogoutRet_Game2GateDefaultTypeInternal _GateUserLogoutRet_Game2Gate_default_instance_;
class GateUserLogout_Gate2Game;
class GateUserLogout_Gate2GameDefaultTypeInternal;
extern GateUserLogout_Gate2GameDefaultTypeInternal _GateUserLogout_Gate2Game_default_instance_;
class GateUserWrapper_Game2Gate;
class GateUserWrapper_Game2GateDefaultTypeInternal;
extern GateUserWrapper_Game2GateDefaultTypeInternal _GateUserWrapper_Game2Gate_default_instance_;
class GateUserWrapper_Gate2Game;
class GateUserWrapper_Gate2GameDefaultTypeInternal;
extern GateUserWrapper_Gate2GameDefaultTypeInternal _GateUserWrapper_Gate2Game_default_instance_;
}  // namespace MPMsg

namespace MPMsg {

namespace protobuf_Gate2Game_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Gate2Game_2eproto

// ===================================================================

class GateUserWrapper_Gate2Game : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MPMsg.GateUserWrapper_Gate2Game) */ {
 public:
  GateUserWrapper_Gate2Game();
  virtual ~GateUserWrapper_Gate2Game();

  GateUserWrapper_Gate2Game(const GateUserWrapper_Gate2Game& from);

  inline GateUserWrapper_Gate2Game& operator=(const GateUserWrapper_Gate2Game& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GateUserWrapper_Gate2Game(GateUserWrapper_Gate2Game&& from) noexcept
    : GateUserWrapper_Gate2Game() {
    *this = ::std::move(from);
  }

  inline GateUserWrapper_Gate2Game& operator=(GateUserWrapper_Gate2Game&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GateUserWrapper_Gate2Game& default_instance();

  static inline const GateUserWrapper_Gate2Game* internal_default_instance() {
    return reinterpret_cast<const GateUserWrapper_Gate2Game*>(
               &_GateUserWrapper_Gate2Game_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GateUserWrapper_Gate2Game* other);
  friend void swap(GateUserWrapper_Gate2Game& a, GateUserWrapper_Gate2Game& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GateUserWrapper_Gate2Game* New() const PROTOBUF_FINAL { return New(NULL); }

  GateUserWrapper_Gate2Game* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GateUserWrapper_Gate2Game& from);
  void MergeFrom(const GateUserWrapper_Gate2Game& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GateUserWrapper_Gate2Game* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes raw_data = 3;
  void clear_raw_data();
  static const int kRawDataFieldNumber = 3;
  const ::std::string& raw_data() const;
  void set_raw_data(const ::std::string& value);
  #if LANG_CXX11
  void set_raw_data(::std::string&& value);
  #endif
  void set_raw_data(const char* value);
  void set_raw_data(const void* value, size_t size);
  ::std::string* mutable_raw_data();
  ::std::string* release_raw_data();
  void set_allocated_raw_data(::std::string* raw_data);

  // uint64 fd = 1;
  void clear_fd();
  static const int kFdFieldNumber = 1;
  ::google::protobuf::uint64 fd() const;
  void set_fd(::google::protobuf::uint64 value);

  // uint64 user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MPMsg.GateUserWrapper_Gate2Game)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr raw_data_;
  ::google::protobuf::uint64 fd_;
  ::google::protobuf::uint64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_Gate2Game_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GateUserWrapper_Game2Gate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MPMsg.GateUserWrapper_Game2Gate) */ {
 public:
  GateUserWrapper_Game2Gate();
  virtual ~GateUserWrapper_Game2Gate();

  GateUserWrapper_Game2Gate(const GateUserWrapper_Game2Gate& from);

  inline GateUserWrapper_Game2Gate& operator=(const GateUserWrapper_Game2Gate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GateUserWrapper_Game2Gate(GateUserWrapper_Game2Gate&& from) noexcept
    : GateUserWrapper_Game2Gate() {
    *this = ::std::move(from);
  }

  inline GateUserWrapper_Game2Gate& operator=(GateUserWrapper_Game2Gate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GateUserWrapper_Game2Gate& default_instance();

  static inline const GateUserWrapper_Game2Gate* internal_default_instance() {
    return reinterpret_cast<const GateUserWrapper_Game2Gate*>(
               &_GateUserWrapper_Game2Gate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GateUserWrapper_Game2Gate* other);
  friend void swap(GateUserWrapper_Game2Gate& a, GateUserWrapper_Game2Gate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GateUserWrapper_Game2Gate* New() const PROTOBUF_FINAL { return New(NULL); }

  GateUserWrapper_Game2Gate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GateUserWrapper_Game2Gate& from);
  void MergeFrom(const GateUserWrapper_Game2Gate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GateUserWrapper_Game2Gate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes raw_data = 2;
  void clear_raw_data();
  static const int kRawDataFieldNumber = 2;
  const ::std::string& raw_data() const;
  void set_raw_data(const ::std::string& value);
  #if LANG_CXX11
  void set_raw_data(::std::string&& value);
  #endif
  void set_raw_data(const char* value);
  void set_raw_data(const void* value, size_t size);
  ::std::string* mutable_raw_data();
  ::std::string* release_raw_data();
  void set_allocated_raw_data(::std::string* raw_data);

  // uint64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MPMsg.GateUserWrapper_Game2Gate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr raw_data_;
  ::google::protobuf::uint64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_Gate2Game_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GameUserLogonSuccess_Game2Gate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MPMsg.GameUserLogonSuccess_Game2Gate) */ {
 public:
  GameUserLogonSuccess_Game2Gate();
  virtual ~GameUserLogonSuccess_Game2Gate();

  GameUserLogonSuccess_Game2Gate(const GameUserLogonSuccess_Game2Gate& from);

  inline GameUserLogonSuccess_Game2Gate& operator=(const GameUserLogonSuccess_Game2Gate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameUserLogonSuccess_Game2Gate(GameUserLogonSuccess_Game2Gate&& from) noexcept
    : GameUserLogonSuccess_Game2Gate() {
    *this = ::std::move(from);
  }

  inline GameUserLogonSuccess_Game2Gate& operator=(GameUserLogonSuccess_Game2Gate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameUserLogonSuccess_Game2Gate& default_instance();

  static inline const GameUserLogonSuccess_Game2Gate* internal_default_instance() {
    return reinterpret_cast<const GameUserLogonSuccess_Game2Gate*>(
               &_GameUserLogonSuccess_Game2Gate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(GameUserLogonSuccess_Game2Gate* other);
  friend void swap(GameUserLogonSuccess_Game2Gate& a, GameUserLogonSuccess_Game2Gate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameUserLogonSuccess_Game2Gate* New() const PROTOBUF_FINAL { return New(NULL); }

  GameUserLogonSuccess_Game2Gate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GameUserLogonSuccess_Game2Gate& from);
  void MergeFrom(const GameUserLogonSuccess_Game2Gate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GameUserLogonSuccess_Game2Gate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 fd = 1;
  void clear_fd();
  static const int kFdFieldNumber = 1;
  ::google::protobuf::uint64 fd() const;
  void set_fd(::google::protobuf::uint64 value);

  // uint64 user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MPMsg.GameUserLogonSuccess_Game2Gate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 fd_;
  ::google::protobuf::uint64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_Gate2Game_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GameUserLogonSuccess_Gate2Game : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MPMsg.GameUserLogonSuccess_Gate2Game) */ {
 public:
  GameUserLogonSuccess_Gate2Game();
  virtual ~GameUserLogonSuccess_Gate2Game();

  GameUserLogonSuccess_Gate2Game(const GameUserLogonSuccess_Gate2Game& from);

  inline GameUserLogonSuccess_Gate2Game& operator=(const GameUserLogonSuccess_Gate2Game& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameUserLogonSuccess_Gate2Game(GameUserLogonSuccess_Gate2Game&& from) noexcept
    : GameUserLogonSuccess_Gate2Game() {
    *this = ::std::move(from);
  }

  inline GameUserLogonSuccess_Gate2Game& operator=(GameUserLogonSuccess_Gate2Game&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameUserLogonSuccess_Gate2Game& default_instance();

  static inline const GameUserLogonSuccess_Gate2Game* internal_default_instance() {
    return reinterpret_cast<const GameUserLogonSuccess_Gate2Game*>(
               &_GameUserLogonSuccess_Gate2Game_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GameUserLogonSuccess_Gate2Game* other);
  friend void swap(GameUserLogonSuccess_Gate2Game& a, GameUserLogonSuccess_Gate2Game& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameUserLogonSuccess_Gate2Game* New() const PROTOBUF_FINAL { return New(NULL); }

  GameUserLogonSuccess_Gate2Game* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GameUserLogonSuccess_Gate2Game& from);
  void MergeFrom(const GameUserLogonSuccess_Gate2Game& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GameUserLogonSuccess_Gate2Game* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 fd = 1;
  void clear_fd();
  static const int kFdFieldNumber = 1;
  ::google::protobuf::uint64 fd() const;
  void set_fd(::google::protobuf::uint64 value);

  // uint64 user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MPMsg.GameUserLogonSuccess_Gate2Game)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 fd_;
  ::google::protobuf::uint64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_Gate2Game_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GateUserLogout_Gate2Game : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MPMsg.GateUserLogout_Gate2Game) */ {
 public:
  GateUserLogout_Gate2Game();
  virtual ~GateUserLogout_Gate2Game();

  GateUserLogout_Gate2Game(const GateUserLogout_Gate2Game& from);

  inline GateUserLogout_Gate2Game& operator=(const GateUserLogout_Gate2Game& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GateUserLogout_Gate2Game(GateUserLogout_Gate2Game&& from) noexcept
    : GateUserLogout_Gate2Game() {
    *this = ::std::move(from);
  }

  inline GateUserLogout_Gate2Game& operator=(GateUserLogout_Gate2Game&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GateUserLogout_Gate2Game& default_instance();

  static inline const GateUserLogout_Gate2Game* internal_default_instance() {
    return reinterpret_cast<const GateUserLogout_Gate2Game*>(
               &_GateUserLogout_Gate2Game_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(GateUserLogout_Gate2Game* other);
  friend void swap(GateUserLogout_Gate2Game& a, GateUserLogout_Gate2Game& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GateUserLogout_Gate2Game* New() const PROTOBUF_FINAL { return New(NULL); }

  GateUserLogout_Gate2Game* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GateUserLogout_Gate2Game& from);
  void MergeFrom(const GateUserLogout_Gate2Game& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GateUserLogout_Gate2Game* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MPMsg.GateUserLogout_Gate2Game)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_Gate2Game_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GateUserLogoutRet_Game2Gate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MPMsg.GateUserLogoutRet_Game2Gate) */ {
 public:
  GateUserLogoutRet_Game2Gate();
  virtual ~GateUserLogoutRet_Game2Gate();

  GateUserLogoutRet_Game2Gate(const GateUserLogoutRet_Game2Gate& from);

  inline GateUserLogoutRet_Game2Gate& operator=(const GateUserLogoutRet_Game2Gate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GateUserLogoutRet_Game2Gate(GateUserLogoutRet_Game2Gate&& from) noexcept
    : GateUserLogoutRet_Game2Gate() {
    *this = ::std::move(from);
  }

  inline GateUserLogoutRet_Game2Gate& operator=(GateUserLogoutRet_Game2Gate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GateUserLogoutRet_Game2Gate& default_instance();

  static inline const GateUserLogoutRet_Game2Gate* internal_default_instance() {
    return reinterpret_cast<const GateUserLogoutRet_Game2Gate*>(
               &_GateUserLogoutRet_Game2Gate_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(GateUserLogoutRet_Game2Gate* other);
  friend void swap(GateUserLogoutRet_Game2Gate& a, GateUserLogoutRet_Game2Gate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GateUserLogoutRet_Game2Gate* New() const PROTOBUF_FINAL { return New(NULL); }

  GateUserLogoutRet_Game2Gate* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GateUserLogoutRet_Game2Gate& from);
  void MergeFrom(const GateUserLogoutRet_Game2Gate& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GateUserLogoutRet_Game2Gate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::uint64 user_id() const;
  void set_user_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:MPMsg.GateUserLogoutRet_Game2Gate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_Gate2Game_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GateUserWrapper_Gate2Game

// uint64 fd = 1;
inline void GateUserWrapper_Gate2Game::clear_fd() {
  fd_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GateUserWrapper_Gate2Game::fd() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserWrapper_Gate2Game.fd)
  return fd_;
}
inline void GateUserWrapper_Gate2Game::set_fd(::google::protobuf::uint64 value) {
  
  fd_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GateUserWrapper_Gate2Game.fd)
}

// uint64 user_id = 2;
inline void GateUserWrapper_Gate2Game::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GateUserWrapper_Gate2Game::user_id() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserWrapper_Gate2Game.user_id)
  return user_id_;
}
inline void GateUserWrapper_Gate2Game::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GateUserWrapper_Gate2Game.user_id)
}

// bytes raw_data = 3;
inline void GateUserWrapper_Gate2Game::clear_raw_data() {
  raw_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GateUserWrapper_Gate2Game::raw_data() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserWrapper_Gate2Game.raw_data)
  return raw_data_.GetNoArena();
}
inline void GateUserWrapper_Gate2Game::set_raw_data(const ::std::string& value) {
  
  raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MPMsg.GateUserWrapper_Gate2Game.raw_data)
}
#if LANG_CXX11
inline void GateUserWrapper_Gate2Game::set_raw_data(::std::string&& value) {
  
  raw_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MPMsg.GateUserWrapper_Gate2Game.raw_data)
}
#endif
inline void GateUserWrapper_Gate2Game::set_raw_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MPMsg.GateUserWrapper_Gate2Game.raw_data)
}
inline void GateUserWrapper_Gate2Game::set_raw_data(const void* value, size_t size) {
  
  raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MPMsg.GateUserWrapper_Gate2Game.raw_data)
}
inline ::std::string* GateUserWrapper_Gate2Game::mutable_raw_data() {
  
  // @@protoc_insertion_point(field_mutable:MPMsg.GateUserWrapper_Gate2Game.raw_data)
  return raw_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GateUserWrapper_Gate2Game::release_raw_data() {
  // @@protoc_insertion_point(field_release:MPMsg.GateUserWrapper_Gate2Game.raw_data)
  
  return raw_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GateUserWrapper_Gate2Game::set_allocated_raw_data(::std::string* raw_data) {
  if (raw_data != NULL) {
    
  } else {
    
  }
  raw_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), raw_data);
  // @@protoc_insertion_point(field_set_allocated:MPMsg.GateUserWrapper_Gate2Game.raw_data)
}

// -------------------------------------------------------------------

// GateUserWrapper_Game2Gate

// uint64 user_id = 1;
inline void GateUserWrapper_Game2Gate::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GateUserWrapper_Game2Gate::user_id() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserWrapper_Game2Gate.user_id)
  return user_id_;
}
inline void GateUserWrapper_Game2Gate::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GateUserWrapper_Game2Gate.user_id)
}

// bytes raw_data = 2;
inline void GateUserWrapper_Game2Gate::clear_raw_data() {
  raw_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GateUserWrapper_Game2Gate::raw_data() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserWrapper_Game2Gate.raw_data)
  return raw_data_.GetNoArena();
}
inline void GateUserWrapper_Game2Gate::set_raw_data(const ::std::string& value) {
  
  raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MPMsg.GateUserWrapper_Game2Gate.raw_data)
}
#if LANG_CXX11
inline void GateUserWrapper_Game2Gate::set_raw_data(::std::string&& value) {
  
  raw_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MPMsg.GateUserWrapper_Game2Gate.raw_data)
}
#endif
inline void GateUserWrapper_Game2Gate::set_raw_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MPMsg.GateUserWrapper_Game2Gate.raw_data)
}
inline void GateUserWrapper_Game2Gate::set_raw_data(const void* value, size_t size) {
  
  raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MPMsg.GateUserWrapper_Game2Gate.raw_data)
}
inline ::std::string* GateUserWrapper_Game2Gate::mutable_raw_data() {
  
  // @@protoc_insertion_point(field_mutable:MPMsg.GateUserWrapper_Game2Gate.raw_data)
  return raw_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GateUserWrapper_Game2Gate::release_raw_data() {
  // @@protoc_insertion_point(field_release:MPMsg.GateUserWrapper_Game2Gate.raw_data)
  
  return raw_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GateUserWrapper_Game2Gate::set_allocated_raw_data(::std::string* raw_data) {
  if (raw_data != NULL) {
    
  } else {
    
  }
  raw_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), raw_data);
  // @@protoc_insertion_point(field_set_allocated:MPMsg.GateUserWrapper_Game2Gate.raw_data)
}

// -------------------------------------------------------------------

// GameUserLogonSuccess_Game2Gate

// uint64 fd = 1;
inline void GameUserLogonSuccess_Game2Gate::clear_fd() {
  fd_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GameUserLogonSuccess_Game2Gate::fd() const {
  // @@protoc_insertion_point(field_get:MPMsg.GameUserLogonSuccess_Game2Gate.fd)
  return fd_;
}
inline void GameUserLogonSuccess_Game2Gate::set_fd(::google::protobuf::uint64 value) {
  
  fd_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GameUserLogonSuccess_Game2Gate.fd)
}

// uint64 user_id = 2;
inline void GameUserLogonSuccess_Game2Gate::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GameUserLogonSuccess_Game2Gate::user_id() const {
  // @@protoc_insertion_point(field_get:MPMsg.GameUserLogonSuccess_Game2Gate.user_id)
  return user_id_;
}
inline void GameUserLogonSuccess_Game2Gate::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GameUserLogonSuccess_Game2Gate.user_id)
}

// -------------------------------------------------------------------

// GameUserLogonSuccess_Gate2Game

// uint64 fd = 1;
inline void GameUserLogonSuccess_Gate2Game::clear_fd() {
  fd_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GameUserLogonSuccess_Gate2Game::fd() const {
  // @@protoc_insertion_point(field_get:MPMsg.GameUserLogonSuccess_Gate2Game.fd)
  return fd_;
}
inline void GameUserLogonSuccess_Gate2Game::set_fd(::google::protobuf::uint64 value) {
  
  fd_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GameUserLogonSuccess_Gate2Game.fd)
}

// uint64 user_id = 2;
inline void GameUserLogonSuccess_Gate2Game::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GameUserLogonSuccess_Gate2Game::user_id() const {
  // @@protoc_insertion_point(field_get:MPMsg.GameUserLogonSuccess_Gate2Game.user_id)
  return user_id_;
}
inline void GameUserLogonSuccess_Gate2Game::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GameUserLogonSuccess_Gate2Game.user_id)
}

// -------------------------------------------------------------------

// GateUserLogout_Gate2Game

// uint64 user_id = 1;
inline void GateUserLogout_Gate2Game::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GateUserLogout_Gate2Game::user_id() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserLogout_Gate2Game.user_id)
  return user_id_;
}
inline void GateUserLogout_Gate2Game::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GateUserLogout_Gate2Game.user_id)
}

// -------------------------------------------------------------------

// GateUserLogoutRet_Game2Gate

// uint64 user_id = 1;
inline void GateUserLogoutRet_Game2Gate::clear_user_id() {
  user_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 GateUserLogoutRet_Game2Gate::user_id() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateUserLogoutRet_Game2Gate.user_id)
  return user_id_;
}
inline void GateUserLogoutRet_Game2Gate::set_user_id(::google::protobuf::uint64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GateUserLogoutRet_Game2Gate.user_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace MPMsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Gate2Game_2eproto__INCLUDED
