// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gate2Super.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Gate2Super.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MPMsg {
class GateVerify_Gate2SuperDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GateVerify_Gate2Super>
     _instance;
} _GateVerify_Gate2Super_default_instance_;
class GateVerify_Super2GateDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<GateVerify_Super2Gate>
     _instance;
} _GateVerify_Super2Gate_default_instance_;

namespace protobuf_Gate2Super_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateVerify_Gate2Super, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateVerify_Super2Gate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GateVerify_Super2Gate, err_code_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(GateVerify_Gate2Super)},
  { 5, -1, sizeof(GateVerify_Super2Gate)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_GateVerify_Gate2Super_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_GateVerify_Super2Gate_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Gate2Super.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _GateVerify_Gate2Super_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_GateVerify_Gate2Super_default_instance_);_GateVerify_Super2Gate_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_GateVerify_Super2Gate_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020Gate2Super.proto\022\005MPMsg\"\027\n\025GateVerify_"
      "Gate2Super\")\n\025GateVerify_Super2Gate\022\020\n\010e"
      "rr_code\030\001 \001(\rb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 101);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Gate2Super.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_Gate2Super_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GateVerify_Gate2Super::GateVerify_Gate2Super()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Gate2Super_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MPMsg.GateVerify_Gate2Super)
}
GateVerify_Gate2Super::GateVerify_Gate2Super(const GateVerify_Gate2Super& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:MPMsg.GateVerify_Gate2Super)
}

void GateVerify_Gate2Super::SharedCtor() {
  _cached_size_ = 0;
}

GateVerify_Gate2Super::~GateVerify_Gate2Super() {
  // @@protoc_insertion_point(destructor:MPMsg.GateVerify_Gate2Super)
  SharedDtor();
}

void GateVerify_Gate2Super::SharedDtor() {
}

void GateVerify_Gate2Super::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GateVerify_Gate2Super::descriptor() {
  protobuf_Gate2Super_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Gate2Super_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GateVerify_Gate2Super& GateVerify_Gate2Super::default_instance() {
  protobuf_Gate2Super_2eproto::InitDefaults();
  return *internal_default_instance();
}

GateVerify_Gate2Super* GateVerify_Gate2Super::New(::google::protobuf::Arena* arena) const {
  GateVerify_Gate2Super* n = new GateVerify_Gate2Super;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GateVerify_Gate2Super::Clear() {
// @@protoc_insertion_point(message_clear_start:MPMsg.GateVerify_Gate2Super)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool GateVerify_Gate2Super::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MPMsg.GateVerify_Gate2Super)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:MPMsg.GateVerify_Gate2Super)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MPMsg.GateVerify_Gate2Super)
  return false;
#undef DO_
}

void GateVerify_Gate2Super::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MPMsg.GateVerify_Gate2Super)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MPMsg.GateVerify_Gate2Super)
}

::google::protobuf::uint8* GateVerify_Gate2Super::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MPMsg.GateVerify_Gate2Super)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MPMsg.GateVerify_Gate2Super)
  return target;
}

size_t GateVerify_Gate2Super::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MPMsg.GateVerify_Gate2Super)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GateVerify_Gate2Super::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MPMsg.GateVerify_Gate2Super)
  GOOGLE_DCHECK_NE(&from, this);
  const GateVerify_Gate2Super* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GateVerify_Gate2Super>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MPMsg.GateVerify_Gate2Super)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MPMsg.GateVerify_Gate2Super)
    MergeFrom(*source);
  }
}

void GateVerify_Gate2Super::MergeFrom(const GateVerify_Gate2Super& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MPMsg.GateVerify_Gate2Super)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GateVerify_Gate2Super::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MPMsg.GateVerify_Gate2Super)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GateVerify_Gate2Super::CopyFrom(const GateVerify_Gate2Super& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MPMsg.GateVerify_Gate2Super)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GateVerify_Gate2Super::IsInitialized() const {
  return true;
}

void GateVerify_Gate2Super::Swap(GateVerify_Gate2Super* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GateVerify_Gate2Super::InternalSwap(GateVerify_Gate2Super* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GateVerify_Gate2Super::GetMetadata() const {
  protobuf_Gate2Super_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Gate2Super_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GateVerify_Gate2Super

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GateVerify_Super2Gate::kErrCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GateVerify_Super2Gate::GateVerify_Super2Gate()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Gate2Super_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MPMsg.GateVerify_Super2Gate)
}
GateVerify_Super2Gate::GateVerify_Super2Gate(const GateVerify_Super2Gate& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  err_code_ = from.err_code_;
  // @@protoc_insertion_point(copy_constructor:MPMsg.GateVerify_Super2Gate)
}

void GateVerify_Super2Gate::SharedCtor() {
  err_code_ = 0u;
  _cached_size_ = 0;
}

GateVerify_Super2Gate::~GateVerify_Super2Gate() {
  // @@protoc_insertion_point(destructor:MPMsg.GateVerify_Super2Gate)
  SharedDtor();
}

void GateVerify_Super2Gate::SharedDtor() {
}

void GateVerify_Super2Gate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GateVerify_Super2Gate::descriptor() {
  protobuf_Gate2Super_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Gate2Super_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GateVerify_Super2Gate& GateVerify_Super2Gate::default_instance() {
  protobuf_Gate2Super_2eproto::InitDefaults();
  return *internal_default_instance();
}

GateVerify_Super2Gate* GateVerify_Super2Gate::New(::google::protobuf::Arena* arena) const {
  GateVerify_Super2Gate* n = new GateVerify_Super2Gate;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GateVerify_Super2Gate::Clear() {
// @@protoc_insertion_point(message_clear_start:MPMsg.GateVerify_Super2Gate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  err_code_ = 0u;
  _internal_metadata_.Clear();
}

bool GateVerify_Super2Gate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MPMsg.GateVerify_Super2Gate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 err_code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &err_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MPMsg.GateVerify_Super2Gate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MPMsg.GateVerify_Super2Gate)
  return false;
#undef DO_
}

void GateVerify_Super2Gate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MPMsg.GateVerify_Super2Gate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 err_code = 1;
  if (this->err_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->err_code(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MPMsg.GateVerify_Super2Gate)
}

::google::protobuf::uint8* GateVerify_Super2Gate::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MPMsg.GateVerify_Super2Gate)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 err_code = 1;
  if (this->err_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->err_code(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MPMsg.GateVerify_Super2Gate)
  return target;
}

size_t GateVerify_Super2Gate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MPMsg.GateVerify_Super2Gate)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 err_code = 1;
  if (this->err_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->err_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GateVerify_Super2Gate::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MPMsg.GateVerify_Super2Gate)
  GOOGLE_DCHECK_NE(&from, this);
  const GateVerify_Super2Gate* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GateVerify_Super2Gate>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MPMsg.GateVerify_Super2Gate)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MPMsg.GateVerify_Super2Gate)
    MergeFrom(*source);
  }
}

void GateVerify_Super2Gate::MergeFrom(const GateVerify_Super2Gate& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MPMsg.GateVerify_Super2Gate)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.err_code() != 0) {
    set_err_code(from.err_code());
  }
}

void GateVerify_Super2Gate::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MPMsg.GateVerify_Super2Gate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GateVerify_Super2Gate::CopyFrom(const GateVerify_Super2Gate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MPMsg.GateVerify_Super2Gate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GateVerify_Super2Gate::IsInitialized() const {
  return true;
}

void GateVerify_Super2Gate::Swap(GateVerify_Super2Gate* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GateVerify_Super2Gate::InternalSwap(GateVerify_Super2Gate* other) {
  using std::swap;
  swap(err_code_, other->err_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GateVerify_Super2Gate::GetMetadata() const {
  protobuf_Gate2Super_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Gate2Super_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GateVerify_Super2Gate

// uint32 err_code = 1;
void GateVerify_Super2Gate::clear_err_code() {
  err_code_ = 0u;
}
::google::protobuf::uint32 GateVerify_Super2Gate::err_code() const {
  // @@protoc_insertion_point(field_get:MPMsg.GateVerify_Super2Gate.err_code)
  return err_code_;
}
void GateVerify_Super2Gate::set_err_code(::google::protobuf::uint32 value) {
  
  err_code_ = value;
  // @@protoc_insertion_point(field_set:MPMsg.GateVerify_Super2Gate.err_code)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace MPMsg

// @@protoc_insertion_point(global_scope)
