// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MPDefine.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MPDefine.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MPMsg {

namespace protobuf_MPDefine_2eproto {


namespace {

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[6];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;
namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "MPDefine.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016MPDefine.proto\022\005MPMsg*\350\001\n\007MsgType\022\023\n\017e"
      "MsgType_Client\020\000\022\031\n\025eMsgType_Super2Cente"
      "r\020\001\022\031\n\025eMsgType_Center2Super\020\002\022\027\n\023eMsgTy"
      "pe_Gate2Super\020\003\022\027\n\023eMsgType_Super2Gate\020\004"
      "\022\027\n\023eMsgType_Game2Super\020\005\022\027\n\023eMsgType_Su"
      "per2Game\020\006\022\026\n\022eMsgType_Gate2Game\020\007\022\026\n\022eM"
      "sgType_Game2Gate\020\010*9\n\016EGameEventCode\022\020\n\014"
      "EGEC_SUCCESS\020\000\022\025\n\021EGEC_UNKOWN_ERROR\020\001*\034\n"
      "\tESynMsgID\022\017\n\013ESMI_UNKNOW\020\000*N\n\nEGameMsgI"
      "D\022\017\n\013EGMI_UNKNOW\020\000\022\025\n\021EGMI_EVENT_RESULT\020"
      "\001\022\030\n\024EGMI_EVENT_TRANSPOND\020\002*C\n\016Gate2Supe"
      "r_Msg\022\027\n\023eGate2Super_Unkonwn\020\000\022\030\n\024eGate2"
      "Super_VerifyMe\020\001*\202\001\n\rGate2Game_Msg\022\024\n\020eG"
      "ameMsg_Unknown\020\000\022\033\n\027eGameMsg_GameMsgWrap"
      "per\020\001\022!\n\035eGameMsg_GameUserLogonSuccess\020\002"
      "\022\033\n\027eGameMsg_GateUserLogout\020\003b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 637);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MPDefine.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_MPDefine_2eproto

const ::google::protobuf::EnumDescriptor* MsgType_descriptor() {
  protobuf_MPDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MPDefine_2eproto::file_level_enum_descriptors[0];
}
bool MsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* EGameEventCode_descriptor() {
  protobuf_MPDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MPDefine_2eproto::file_level_enum_descriptors[1];
}
bool EGameEventCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ESynMsgID_descriptor() {
  protobuf_MPDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MPDefine_2eproto::file_level_enum_descriptors[2];
}
bool ESynMsgID_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* EGameMsgID_descriptor() {
  protobuf_MPDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MPDefine_2eproto::file_level_enum_descriptors[3];
}
bool EGameMsgID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Gate2Super_Msg_descriptor() {
  protobuf_MPDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MPDefine_2eproto::file_level_enum_descriptors[4];
}
bool Gate2Super_Msg_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* Gate2Game_Msg_descriptor() {
  protobuf_MPDefine_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MPDefine_2eproto::file_level_enum_descriptors[5];
}
bool Gate2Game_Msg_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MPMsg

// @@protoc_insertion_point(global_scope)
