// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserMsgDefine.proto

#ifndef PROTOBUF_UserMsgDefine_2eproto__INCLUDED
#define PROTOBUF_UserMsgDefine_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_UserMsgDefine_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_UserMsgDefine_2eproto

enum UserMsgDefine {
  UserMsg_Unknown = 0,
  UserMsg_Logon = 1,
  UserMsg_CreateRole = 2,
  UserMsgDefine_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  UserMsgDefine_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool UserMsgDefine_IsValid(int value);
const UserMsgDefine UserMsgDefine_MIN = UserMsg_Unknown;
const UserMsgDefine UserMsgDefine_MAX = UserMsg_CreateRole;
const int UserMsgDefine_ARRAYSIZE = UserMsgDefine_MAX + 1;

const ::google::protobuf::EnumDescriptor* UserMsgDefine_descriptor();
inline const ::std::string& UserMsgDefine_Name(UserMsgDefine value) {
  return ::google::protobuf::internal::NameOfEnum(
    UserMsgDefine_descriptor(), value);
}
inline bool UserMsgDefine_Parse(
    const ::std::string& name, UserMsgDefine* value) {
  return ::google::protobuf::internal::ParseNamedEnum<UserMsgDefine>(
    UserMsgDefine_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::UserMsgDefine> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::UserMsgDefine>() {
  return ::UserMsgDefine_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UserMsgDefine_2eproto__INCLUDED
